# Generated by Django 5.0.13 on 2025-05-08 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefon', models.TextField(blank=True, null=True)),
                ('kjønn', models.TextField(blank=True, null=True)),
                ('kull', models.TextField(blank=True, null=True)),
                ('erfaren', models.BooleanField(default=False)),
                ('pu_erfaren', models.BooleanField(default=False)),
                ('fus_erfaren', models.BooleanField(default=False)),
                ('over_72h', models.BooleanField(default=False)),
                ('internundervisning', models.BooleanField(default=False)),
                ('styremedlem', models.BooleanField(default=False)),
            ],
        ),
    ]
