# Generated by Django 5.0.13 on 2025-05-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_profile_timer_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kjønn',
            field=models.CharField(blank=True, choices=[('M', 'Mann'), ('K', 'Kvinne'), ('A', 'Annet')], max_length=1, null=True),
        ),
    ]
