# Generated by Django 5.0.13 on 2025-05-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_profile_kjønn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='over_72h',
        ),
    ]
