# Generated by Django 5.0.13 on 2025-05-11 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_profile_over_72h'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_is_active', models.BooleanField(default=False)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='job', to='management.profile')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='wagtailforms.formsubmission')),
            ],
        ),
    ]
