# Generated by Django 5.0.13 on 2025-05-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_to_F',
            field=models.ManyToManyField(default=None, related_name='assigned_to_F', to='management.profile'),
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_to_M',
            field=models.ManyToManyField(default=None, related_name='assigned_to_M', to='management.profile'),
        ),
    ]
