# Generated by Django 5.0.13 on 2025-05-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_job_assigned_to_job_assigned_to_f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kjønn',
            field=models.CharField(blank=True, choices=[('M', 'Mann'), ('K', 'Kvinne')], max_length=1, null=True),
        ),
    ]
