# Generated by Django 5.0.13 on 2025-05-11 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_profile_kjønn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='assigned_to_F',
        ),
        migrations.RemoveField(
            model_name='job',
            name='assigned_to_M',
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_to_F',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to_F', to='management.profile'),
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_to_M',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to_M', to='management.profile'),
        ),
    ]
