# Generated by Django 5.0.13 on 2025-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_job_assigned_to_f_remove_job_assigned_to_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
