# Generated by Django 5.0.13 on 2025-05-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_job_job_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='days_since_last_job',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_job_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
