# Generated by Django 5.0.13 on 2025-05-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_profile_days_since_last_job_profile_last_job_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='days_since_last_job',
            new_name='months_since_last_job',
        ),
    ]
