# Generated by Django 5.0.9 on 2024-10-10 17:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_hero_cta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Write an introduction for the site', max_length=255),
        ),
    ]
