# Generated by Django 5.0.9 on 2024-10-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_body'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='DefaultPage',
        ),
    ]
